version: "3.5"

services:
  api01: &postgrest
    image: postgrest/postgrest:latest
    environment:
      PGRST_DB_URI: postgres://admin:123@db:5432/rinha
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: "web_anon" # Replace this with your actual anonymous role if you have one
      PGRST_SERVER_PORT: "8080"
    depends_on:
      - db
    ports:
      - "8081:8080" # PostgREST runs on port 3000 by default
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"

  api02:
    <<: *postgrest
    ports:
      - "8082:8080"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "140MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1