version: "3.5"

services:
  api01: &postgrest
    image: postgrest/postgrest
    environment:
      PGRST_DB_URI: postgres://admin:123@pgbouncer:6432/rinha
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: "web_anon"
      PGRST_SERVER_PORT: "8080"
      PGRST_DB_POOL: 50
      PGRST_DB_POOL_MAX_IDLETIME: 500  # value in seconds
      PGRST_DB_POOL_AUTOMATIC_RECOVERY: "False"
      PGRST_DB_PREPARED_STATEMENTS: "False"
    depends_on:
      - pgbouncer
    ports:
      - "8081:8080"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "100MB"

  api02:
    <<: *postgrest
    ports:
      - "8082:8080"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "100MB"

  nginx:
    image: openresty/openresty:alpine-fat
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "40MB"

  db:
    image: postgres:16-alpine3.19
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "280MB"

  pgbouncer:
    image: bitnami/pgbouncer
    environment:
      - PGBOUNCER_DATABASES=*:host=db port=5432
      - POSTGRESQL_HOST=db
      - POSTGRESQL_PASSWORD=123
      - PGBOUNCER_LISTEN_PORT=6432
      - PGBOUNCER_LISTEN_ADDR=*
      - PGBOUNCER_ADMIN_USERS=admin
    volumes:
      - ./pgbouncer.ini:/bitnami/pgbouncer/conf/pgbouncer.ini
      - ./userlist.txt:/etc/pgbouncer/userlist.txt
    depends_on:
      - db
    ports:
      - "6432:6432"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "30MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
